# Generated by Django 4.2.1 on 2023-06-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_author_category_comment_post_postcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categotyType',
            new_name='categoryType',
        ),
    ]
